config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  root :to => 'projects#index'
  
  map.resources :sessions, :only => [:new, :create, :destroy]
  map.resources :businesses, :only => [:index]
  
  map.resources :sugestions
  map.resources :projects
  map.resources :users
  map.resources :components
  map.resources :pcomponents
  map.resources :questions
  map.resources :requirements
  map.resources :prequirements 
  map.resources :pquestions, :member => {:rate => :post}
  

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"

   root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :pcomponents, :dependent => :destroy
  has_many :pquestions, :dependent => :destroy
  has_many :prequirements, :dependent => :destroy
  
  validates :title, :presence =>true
  validates :due_date, :presence =>true
  

  cattr_reader :per_page
  @@per_page =  1
  
  
  def did_finish
    components_finished = 0
    score = 0.0
    requirement_aproved = true
    
      self.pcomponents.each do |pc|
        if pc.questions_finished
           components_finished =  components_finished + 1
           score += pc.questions_score
        end
        if !pc.requirements_aproved
          requirement_aproved = false
        end
      end
      if pcomponents.count == components_finished
        score /= components_finished
        if requirement_aproved && score >= 3.0
          self.state = 'Aproved'
        else
          self.state = 'Unaproved'
        end
        self.score = score
      else
        self.state = 'In process'
      end
      self.save
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  
  respond_to :html, :xml
  
  
  def index
    @projects = Project.paginate :page => params[:page]
    respond_with @projects
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_with @project
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_with @project
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    
    new_was_successful = @project.save

      respond_with(@project) do |format|
        format.html {
          if new_was_successful
            components = Component.all
            components.each do |c|
              pc = Pcomponent.new
              pc.project = @project
              pc.component = c
              pc.save
            end
            
            questions = Question.all
            questions.each do |q|
              pq = Pquestion.new
              pq.project = @project
              pq.question = q
              pq.save
            end
            
            
            requirements = Requirement.all
            requirements.each do |r|
              pr = Prequirement.new
              pr.project = @project
              pr.requirement = r
              pr.save
            end
            
            redirect_to(project_path(@project), :notice => "The project was successfully created")
          else
            render 'new'
          end
        }
      end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])
    
     updated_was_successful = @project.update_attributes(params[:project])

      respond_with(@project) do |format|
        format.html {
          if updated_was_successful
            redirect_to(project_path(@project), :notice => "The project was successfully updated")
          else
            render 'edit'
          end
        }
      end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_with @project
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
   def project_title_links(project)
    content_tag :h1 do
      [project.title,
      link_to_icon('show', project_path(project)+'?type=2'),
      link_to_icon('edit', edit_project_path(project)),
        link_to_icon('destroy', project, {
          :confirm => 'Are you sure?',
          :method => :delete
        })
      ].join(' ').html_safe
    end
  end
  
end

app/views/projects/_form.html.erb
<%= semantic_form_for(@project) do |form| %>
	  <%= form.inputs "" do %>
    		<%= form.input :title %>
			<%= form.input :due_date %>
  	  <% end %>
	  <%= form.buttons do %>
      <%= form.commit_button "Submit" %>
   <% end %>

<% end %>

app/views/projects/_project.html.erb
<div class="field">
	<%= project_title_links(project)%>
	<div class="project-state"><% if !project.state.nil? %> <%= project.state %> <%end%></div>
	<div class="project-score"><% if !project.score.nil? %> <%=  "%.2f"%(project.score.to_s) %><%end%></div>
	<%= render project.pcomponents %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<p class="addlink"><%= link_to 'Create a new project', new_project_path()%></p>
<%= render @projects %>
<%= will_paginate @posts %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= render @project%>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>